name: update Model Repository

on: 
  repository_dispatch:
    types:
      - update

jobs:
#copies and replaces the updated models of the repository which triggered this action
  update-models:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout THIS repository first
        uses: actions/checkout@v4
       
      - name: Checkout the repo that triggered this workflow
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.sha }}
          path: source_repo

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          
      - name: See what has Changed
        run: |
          echo "---------------------------------------------"
          echo "Repo: ${{ github.event.client_payload.repo }}"
          echo "SHA:  ${{ github.event.client_payload.sha }}"
          echo "Ref:  ${{ github.event.client_payload.ref }}"
          echo "Add:  ${{ github.event.client_payload.add }}"
          echo "Modify:  ${{ github.event.client_payload.modify }}"
          echo "Delete:  ${{ github.event.client_payload.delete }}"
      
      - name: add new Models to the Model Repository
        id: add
        run: |
          files=()
          
          if [ "${{ github.event.client_payload.add }}" != "" ]; then
            IFS=',' read -ra add_paths <<< "${{ github.event.client_payload.add }}"
            
            for add_path in "${add_paths[@]}"; do
              folder=$(dirname "$add_path")
              file=$(basename "$add_path")
              cd "source_repo/$folder"
              cp -v "$file" ../../repository
              cd ../..
              files+=("$file")
            done
          fi
          
          files_str=$(IFS=,; echo "${files[*]}")
          echo "files=$files_str" >> "$GITHUB_OUTPUT"
          
      - name: modlify Models in the Model Repository
        id: modify
        run: |
          files=()
          
          if [ "${{ github.event.client_payload.modify }}" != "" ]; then          
            IFS=',' read -ra mod_paths <<< "${{ github.event.client_payload.modify }}"
            
            for mod_path in "${mod_paths[@]}"; do
              folder=$(dirname "$mod_path")
              file=$(basename "$mod_path")
              cd "source_repo/$folder"
              cp -v "$file" ../../repository
              cd ../..
              files+=("$file")
            done
          fi
          
          files_str=$(IFS=,; echo "${files[*]}")
          echo "files=$files_str" >> "$GITHUB_OUTPUT"
          
      - name: Commit the Changes to the GitRepo
        run: |
          if [ "${{ github.event.client_payload.add }}" != "" ]; then
            files="${{ steps.add.outputs.files }}"
            git add repository/*.ili
            git diff-index --quiet HEAD || (git commit -m "Files $files added to the repository" && git push)
          fi
          
          if [ "${{ github.event.client_payload.modify }}" != "" ]; then
            files="${{ steps.modify.outputs.files }}"
            git add repository/*.ili
            git diff-index --quiet HEAD || (git commit -m "Files $files modified in the repository" && git push)
          fi
           
          git log --oneline -5
